import {
  Gamepad2,
  Code,
  Server,
  Cpu,
  Wrench,
  Crosshair,
  Layers,
  Database,
  Cloud,
  Lock,
  Globe,
  Smartphone,
  Camera,
  Video,
  Sparkles,
  Palette,
  Atom,
  Network,
  Zap,
  Move,
  Heart,
  Bot,
  Flag,
  GitBranch,
  Github,
  Cog,
  Boxes,
  Film,
  Clapperboard,
  User,
  ArrowUp,
  Package,
  LayoutGrid,
  Monitor,
  Coffee,
  Brush,
  Swords,
  Workflow,
  Plug,
  BoxSelect,
  Footprints,
  type LucideIcon,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  unity: Gamepad2,
  csharp: Code,
  sql: Database,
  gameplay: Crosshair,
  architecture: Cpu,
  state_machine: GitBranch,
  character: User,
  combat: Swords,
  animation: Clapperboard,
  animator: Film,
  cinemachine: Camera,
  particle: Sparkles,
  urp: Palette,
  physics: Atom,
  netcode: Network,
  webgl: Globe,
  mobile: Smartphone,
  auth: Lock,
  cloud: Cloud,
  coyote: Footprints,
  jump: ArrowUp,
  wall: Move,
  dash: Zap,
  fsm: Workflow,
  movement: Move,
  input: Gamepad2,
  feel: Heart,
  enemy: Bot,
  camera: Video,
  collision: BoxSelect,
  checkpoint: Flag,
  html: Code,
  css: Brush,
  java: Coffee,
  javascript: Code,
  aspnet: Server,
  dotnet: Layers,
  ef: Database,
  sqlserver: Database,
  rest: Plug,
  unreal: Boxes,
  godot: Cog,
  vs: Monitor,
  vsc: Code,
  git: GitBranch,
  github: Github,
  unity_hub: LayoutGrid,
  upm: Package,
}

export function getSkillIcon(iconKey: string): LucideIcon {
  return ICON_MAP[iconKey] || Code
}

export const SKILL_CONNECTIONS: Array<[string, string]> = [
  ['Unity Engine', 'C#'],
  ['Unity Engine', 'Cinemachine'],
  ['Unity Engine', 'Universal Render Pipeline (URP)'],
  ['Unity Engine', 'Netcode for GameObjects'],
  ['ASP.NET MVC', 'Entity Framework'],
  ['Entity Framework', 'SQL Server'],
  ['C#', 'Gameplay Programming'],
  ['Gameplay Programming', 'State Machines'],
  ['Gameplay Programming', 'Combat Systems'],
  ['Gameplay Programming', 'Character Controller'],
]

export const CATEGORY_TAB_ICONS: Record<string, LucideIcon> = {
  all: Cpu,
  game_dev: Gamepad2,
  gameplay: Crosshair,
  languages: Code,
  backend: Server,
  engines: Boxes,
  frameworks: Layers,
  tools: Wrench,
}
