import pb from '@/lib/pocketbase/client'
import { normalizeLevel, getCategories } from '@/lib/skill-config'

export interface SkillRecord {
  id: string
  category: string
  categories: string[]
  name_pt: string
  name_en: string
  name_es: string
  description_pt: string
  description_en: string
  description_es: string
  level: number
  tags: string[]
  icon: string
  order: number
}

export const getSkills = async (): Promise<SkillRecord[]> => {
  try {
    const records = await pb.collection('skills').getFullList<any>({ sort: 'order' })
    return records.map((r) => ({
      id: r.id,
      category: r.category || '',
      categories: getCategories(r.categories, r.category),
      name_pt: r.name_pt || r.name_en || '',
      name_en: r.name_en || r.name_pt || '',
      name_es: r.name_es || r.name_en || '',
      description_pt: r.description_pt || '',
      description_en: r.description_en || '',
      description_es: r.description_es || '',
      level: normalizeLevel(r.level || 2),
      tags: Array.isArray(r.tags) ? r.tags : [],
      icon: r.icon || 'gameplay',
      order: r.order || 0,
    }))
  } catch (err) {
    console.warn('Failed to fetch skills from PocketBase, returning fallback dataset:', err)
    return [
      {
        id: '1',
        category: 'game_dev',
        categories: ['game_dev', 'engines'],
        name_pt: 'Unity Engine (2D/3D)',
        name_en: 'Unity Engine (2D/3D)',
        name_es: 'Unity Engine (2D/3D)',
        description_pt: 'Motor principal para jogos 2D e 3D',
        description_en: 'Primary engine for 2D and 3D games',
        description_es: 'Motor principal para juegos 2D y 3D',
        level: 3,
        tags: ['2D', '3D', 'C#'],
        icon: 'unity',
        order: 1,
      },
      {
        id: '2',
        category: 'game_dev',
        categories: ['game_dev', 'gameplay'],
        name_pt: 'Gameplay Programming',
        name_en: 'Gameplay Programming',
        name_es: 'Programacion Gameplay',
        description_pt: 'Programacao de mecanicas e sistemas',
        description_en: 'Gameplay mechanics and systems',
        description_es: 'Mecanicas y sistemas de jugabilidad',
        level: 3,
        tags: ['Mechanics', 'Systems'],
        icon: 'gameplay',
        order: 2,
      },
      {
        id: '3',
        category: 'game_dev',
        categories: ['game_dev', 'gameplay'],
        name_pt: 'State Machines',
        name_en: 'State Machines',
        name_es: 'State Machines',
        description_pt: 'FSM modular para personagens',
        description_en: 'Modular FSM for characters',
        description_es: 'FSM modular para personajes',
        level: 3,
        tags: ['FSM', 'AI'],
        icon: 'state-machine',
        order: 4,
      },
      {
        id: '4',
        category: 'game_dev',
        categories: ['game_dev', 'gameplay'],
        name_pt: 'Combat Systems',
        name_en: 'Combat Systems',
        name_es: 'Sistemas de Combate',
        description_pt: 'Hitboxes, Hurtboxes e Hitstop',
        description_en: 'Hitboxes, Hurtboxes and Hitstop',
        description_es: 'Hitboxes, Hurtboxes y Hitstop',
        level: 3,
        tags: ['Combat', 'Feedback'],
        icon: 'combat',
        order: 6,
      },
      {
        id: '5',
        category: 'languages',
        categories: ['languages'],
        name_pt: 'C#',
        name_en: 'C#',
        name_es: 'C#',
        description_pt: 'Linguagem principal para Unity e .NET',
        description_en: 'Primary language for Unity and .NET',
        description_es: 'Lenguaje principal para Unity y .NET',
        level: 3,
        tags: ['OOP', 'LINQ'],
        icon: 'csharp',
        order: 29,
      },
      {
        id: '6',
        category: 'backend',
        categories: ['backend', 'frameworks'],
        name_pt: 'ASP.NET MVC',
        name_en: 'ASP.NET MVC',
        name_es: 'ASP.NET MVC',
        description_pt: 'Framework MVC para web em C#',
        description_en: 'MVC framework for C# web apps',
        description_es: 'Framework MVC para web en C#',
        level: 2,
        tags: ['MVC', 'Web'],
        icon: 'aspnet',
        order: 35,
      },
      {
        id: '7',
        category: 'backend',
        categories: ['backend', 'frameworks'],
        name_pt: 'Entity Framework',
        name_en: 'Entity Framework',
        name_es: 'Entity Framework',
        description_pt: 'ORM para .NET',
        description_en: 'ORM for .NET',
        description_es: 'ORM para .NET',
        level: 2,
        tags: ['ORM', 'Migrations'],
        icon: 'ef',
        order: 37,
      },
      {
        id: '8',
        category: 'backend',
        categories: ['backend'],
        name_pt: 'SQL Server',
        name_en: 'SQL Server',
        name_es: 'SQL Server',
        description_pt: 'Banco de dados relacional',
        description_en: 'Relational database',
        description_es: 'Base de datos relacional',
        level: 2,
        tags: ['Database', 'T-SQL'],
        icon: 'sql-server',
        order: 38,
      },
      {
        id: '9',
        category: 'game_dev',
        categories: ['game_dev', 'frameworks'],
        name_pt: 'Cinemachine',
        name_en: 'Cinemachine',
        name_es: 'Cinemachine',
        description_pt: 'Cameras dinamicas em Unity',
        description_en: 'Dynamic cameras in Unity',
        description_es: 'Cameras dinamicas en Unity',
        level: 3,
        tags: ['Camera', 'Cinematic'],
        icon: 'cinemachine',
        order: 9,
      },
      {
        id: '10',
        category: 'game_dev',
        categories: ['game_dev'],
        name_pt: 'Universal Render Pipeline (URP)',
        name_en: 'Universal Render Pipeline (URP)',
        name_es: 'Universal Render Pipeline (URP)',
        description_pt: 'Pipeline otimizado de renderizacao',
        description_en: 'Optimized render pipeline',
        description_es: 'Pipeline optimizado de renderizado',
        level: 3,
        tags: ['Rendering', 'Shaders'],
        icon: 'urp',
        order: 11,
      },
      {
        id: '11',
        category: 'game_dev',
        categories: ['game_dev', 'frameworks'],
        name_pt: 'Netcode for GameObjects',
        name_en: 'Netcode for GameObjects',
        name_es: 'Netcode for GameObjects',
        description_pt: 'Multiplayer em tempo real',
        description_en: 'Real-time multiplayer',
        description_es: 'Multijugador en tiempo real',
        level: 1,
        tags: ['Multiplayer', 'Networking'],
        icon: 'netcode',
        order: 13,
      },
      {
        id: '12',
        category: 'game_dev',
        categories: ['game_dev', 'gameplay'],
        name_pt: 'Character Controller',
        name_en: 'Character Controller',
        name_es: 'Character Controller',
        description_pt: 'Controlador com Coyote Time',
        description_en: 'Controller with Coyote Time',
        description_es: 'Controlador con Coyote Time',
        level: 3,
        tags: ['Movement', 'Precision'],
        icon: 'controller',
        order: 5,
      },
    ]
  }
}
