migrate(
  (app) => {
    const collections = [
      {
        name: 'projects',
        type: 'base',
        listRule: '',
        viewRule: '',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        fields: [
          { name: 'slug', type: 'text', required: true },
          { name: 'title_pt', type: 'text', required: true },
          { name: 'title_en', type: 'text', required: true },
          { name: 'title_es', type: 'text', required: true },
          { name: 'subtitle_pt', type: 'text' },
          { name: 'subtitle_en', type: 'text' },
          { name: 'subtitle_es', type: 'text' },
          { name: 'description_pt', type: 'text' },
          { name: 'description_en', type: 'text' },
          { name: 'description_es', type: 'text' },
          { name: 'content_pt', type: 'text' },
          { name: 'content_en', type: 'text' },
          { name: 'content_es', type: 'text' },
          {
            name: 'category',
            type: 'select',
            required: true,
            values: ['game', 'backend', 'tool', 'experiment'],
            maxSelect: 1,
          },
          { name: 'tech', type: 'json' },
          { name: 'cover_image', type: 'file', maxSelect: 1, maxSize: 5242880 },
          { name: 'gallery', type: 'json' },
          { name: 'video_url', type: 'text' },
          { name: 'github_url', type: 'text' },
          { name: 'itch_url', type: 'text' },
          { name: 'demo_url', type: 'text' },
          { name: 'featured', type: 'bool' },
          { name: 'order', type: 'number' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: [
          'CREATE UNIQUE INDEX idx_projects_slug ON projects (slug)',
          'CREATE INDEX idx_projects_cat_order ON projects (category, "order")',
        ],
      },
      {
        name: 'experience',
        type: 'base',
        listRule: '',
        viewRule: '',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        fields: [
          { name: 'role_pt', type: 'text', required: true },
          { name: 'role_en', type: 'text', required: true },
          { name: 'role_es', type: 'text', required: true },
          { name: 'company', type: 'text' },
          { name: 'period', type: 'text' },
          { name: 'description_pt', type: 'text' },
          { name: 'description_en', type: 'text' },
          { name: 'description_es', type: 'text' },
          { name: 'tags', type: 'json' },
          { name: 'order', type: 'number' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: ['CREATE INDEX idx_exp_order ON experience ("order")'],
      },
      {
        name: 'timeline',
        type: 'base',
        listRule: '',
        viewRule: '',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        fields: [
          { name: 'year', type: 'text' },
          { name: 'title_pt', type: 'text' },
          { name: 'title_en', type: 'text' },
          { name: 'title_es', type: 'text' },
          { name: 'description_pt', type: 'text' },
          { name: 'description_en', type: 'text' },
          { name: 'description_es', type: 'text' },
          { name: 'order', type: 'number' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: ['CREATE INDEX idx_timeline_order ON timeline ("order")'],
      },
      {
        name: 'skills',
        type: 'base',
        listRule: '',
        viewRule: '',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        fields: [
          {
            name: 'category',
            type: 'select',
            required: true,
            values: [
              'gameplay',
              'backend',
              'languages',
              'engines',
              'frameworks',
              'tools',
              'versioning',
            ],
            maxSelect: 1,
          },
          { name: 'name_pt', type: 'text' },
          { name: 'name_en', type: 'text' },
          { name: 'name_es', type: 'text' },
          { name: 'level', type: 'number' },
          { name: 'order', type: 'number' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: ['CREATE INDEX idx_skills_cat ON skills (category)'],
      },
      {
        name: 'stack',
        type: 'base',
        listRule: '',
        viewRule: '',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        fields: [
          { name: 'category', type: 'text' },
          { name: 'items', type: 'json' },
          { name: 'order', type: 'number' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: ['CREATE INDEX idx_stack_cat ON stack (category)'],
      },
      {
        name: 'certificates',
        type: 'base',
        listRule: '',
        viewRule: '',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        fields: [
          { name: 'title', type: 'text' },
          {
            name: 'issuer',
            type: 'select',
            required: true,
            values: ['Unity', 'GameDev.tv', 'Udemy', 'Unity Technologies'],
            maxSelect: 1,
          },
          { name: 'year', type: 'text' },
          {
            name: 'category',
            type: 'select',
            required: true,
            values: ['unity', 'gamedev', 'udemy', 'unitytech'],
            maxSelect: 1,
          },
          { name: 'link', type: 'text' },
          { name: 'image', type: 'file', maxSelect: 1 },
          { name: 'order', type: 'number' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: ['CREATE INDEX idx_cert_cat_year ON certificates (category, year)'],
      },
      {
        name: 'game_systems',
        type: 'base',
        listRule: '',
        viewRule: '',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        fields: [
          { name: 'title_pt', type: 'text' },
          { name: 'title_en', type: 'text' },
          { name: 'title_es', type: 'text' },
          { name: 'description_pt', type: 'text' },
          { name: 'description_en', type: 'text' },
          { name: 'description_es', type: 'text' },
          { name: 'icon', type: 'text' },
          { name: 'order', type: 'number' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: ['CREATE INDEX idx_systems_order ON game_systems ("order")'],
      },
      {
        name: 'game_jam',
        type: 'base',
        listRule: '',
        viewRule: '',
        createRule: null,
        updateRule: null,
        deleteRule: null,
        fields: [
          { name: 'title', type: 'text' },
          { name: 'year', type: 'text' },
          { name: 'description_pt', type: 'text' },
          { name: 'description_en', type: 'text' },
          { name: 'description_es', type: 'text' },
          { name: 'images', type: 'json' },
          { name: 'links', type: 'json' },
          { name: 'order', type: 'number' },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: ['CREATE INDEX idx_jam_order ON game_jam ("order")'],
      },
      {
        name: 'contact_messages',
        type: 'base',
        listRule: null,
        viewRule: null,
        createRule: '',
        updateRule: null,
        deleteRule: null,
        fields: [
          { name: 'name', type: 'text', required: true },
          { name: 'email', type: 'text', required: true },
          { name: 'subject', type: 'text' },
          { name: 'message', type: 'text', required: true },
          {
            name: 'status',
            type: 'select',
            required: true,
            values: ['new', 'read', 'archived'],
            maxSelect: 1,
          },
          { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
          { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
        ],
        indexes: ['CREATE INDEX idx_msg_status ON contact_messages (status)'],
      },
    ]

    for (const col of collections) {
      const collection = new Collection(col)
      app.save(collection)
    }
  },
  (app) => {
    const names = [
      'contact_messages',
      'game_jam',
      'game_systems',
      'certificates',
      'stack',
      'skills',
      'timeline',
      'experience',
      'projects',
    ]
    for (const name of names) {
      try {
        const c = app.findCollectionByNameOrId(name)
        app.delete(c)
      } catch (_) {}
    }
  },
)
