migrate(
  (app) => {
    if (!app.hasTable('skills')) return

    var skills = [
      {
        name_pt: 'Unity Engine (2D/3D)',
        name_en: 'Unity Engine (2D/3D)',
        name_es: 'Unity Engine (2D/3D)',
        description_pt: 'Motor principal para desenvolvimento de jogos 2D e 3D',
        description_en: 'Primary engine for 2D and 3D game development',
        description_es: 'Motor principal para desarrollo de juegos 2D y 3D',
        level: 3,
        category: 'engines',
        categories: ['game_dev', 'engines'],
        tags: ['2D', '3D', 'C#', 'URP', 'Cross-platform'],
        icon: 'unity',
        order: 1,
      },
      {
        name_pt: 'Gameplay Programming',
        name_en: 'Gameplay Programming',
        name_es: 'Programacion Gameplay',
        description_pt: 'Programacao de mecanicas e sistemas de jogabilidade',
        description_en: 'Programming of gameplay mechanics and systems',
        description_es: 'Programacion de mecanicas y sistemas de jugabilidad',
        level: 3,
        category: 'gameplay',
        categories: ['game_dev', 'gameplay'],
        tags: ['Mechanics', 'Systems', 'Game Feel'],
        icon: 'gameplay',
        order: 2,
      },
      {
        name_pt: 'Game Architecture',
        name_en: 'Game Architecture',
        name_es: 'Arquitectura de Juegos',
        description_pt: 'Sistemas desacoplados, ScriptableObjects e Event Channels',
        description_en: 'Decoupled systems, ScriptableObjects and Event Channels',
        description_es: 'Sistemas desacoplados, ScriptableObjects y Event Channels',
        level: 3,
        category: 'gameplay',
        categories: ['game_dev'],
        tags: ['ScriptableObjects', 'Events', 'Patterns'],
        icon: 'architecture',
        order: 3,
      },
      {
        name_pt: 'State Machines',
        name_en: 'State Machines',
        name_es: 'State Machines',
        description_pt: 'FSM modular para controle de estados de personagem',
        description_en: 'Modular FSM for character state management',
        description_es: 'FSM modular para gestion de estados de personaje',
        level: 3,
        category: 'gameplay',
        categories: ['game_dev', 'gameplay'],
        tags: ['FSM', 'AI', 'Character'],
        icon: 'state-machine',
        order: 4,
      },
      {
        name_pt: 'Character Controller',
        name_en: 'Character Controller',
        name_es: 'Character Controller',
        description_pt: 'Controlador preciso com Coyote Time e Jump Buffer',
        description_en: 'Precise controller with Coyote Time and Jump Buffer',
        description_es: 'Controlador preciso con Coyote Time y Jump Buffer',
        level: 3,
        category: 'gameplay',
        categories: ['game_dev', 'gameplay'],
        tags: ['Movement', 'Physics', 'Precision'],
        icon: 'controller',
        order: 5,
      },
      {
        name_pt: 'Combat Systems',
        name_en: 'Combat Systems',
        name_es: 'Sistemas de Combate',
        description_pt: 'Hitboxes, Hurtboxes, Hitstop e Camera Shake',
        description_en: 'Hitboxes, Hurtboxes, Hitstop and Camera Shake',
        description_es: 'Hitboxes, Hurtboxes, Hitstop y Camera Shake',
        level: 3,
        category: 'gameplay',
        categories: ['game_dev', 'gameplay'],
        tags: ['Hitbox', 'Combat', 'Feedback'],
        icon: 'combat',
        order: 6,
      },
      {
        name_pt: 'Animation',
        name_en: 'Animation',
        name_es: 'Animacion',
        description_pt: 'Sistemas de animacao 2D e 3D em Unity',
        description_en: '2D and 3D animation systems in Unity',
        description_es: 'Sistemas de animacion 2D y 3D en Unity',
        level: 2,
        category: 'gameplay',
        categories: ['game_dev'],
        tags: ['2D', '3D', 'Rigging'],
        icon: 'animation',
        order: 7,
      },
      {
        name_pt: 'Animator',
        name_en: 'Animator',
        name_es: 'Animator',
        description_pt: 'Controller Animator com Blend Trees e parametros',
        description_en: 'Animator Controller with Blend Trees and parameters',
        description_es: 'Animator Controller con Blend Trees y parametros',
        level: 2,
        category: 'gameplay',
        categories: ['game_dev'],
        tags: ['Blend Trees', 'Parameters', 'Transitions'],
        icon: 'animator',
        order: 8,
      },
      {
        name_pt: 'Cinemachine',
        name_en: 'Cinemachine',
        name_es: 'Cinemachine',
        description_pt: 'Cameras dinamicas e cinematograficas em Unity',
        description_en: 'Dynamic and cinematic cameras in Unity',
        description_es: 'Cameras dinamicas y cinematograficas en Unity',
        level: 3,
        category: 'frameworks',
        categories: ['game_dev', 'frameworks'],
        tags: ['Camera', 'Cinematic', 'Tracking'],
        icon: 'cinemachine',
        order: 9,
      },
      {
        name_pt: 'Particle System',
        name_en: 'Particle System',
        name_es: 'Particle System',
        description_pt: 'Efeitos visuais e particulas para feedback de gameplay',
        description_en: 'Visual effects and particles for gameplay feedback',
        description_es: 'Efectos visuales y particulas para feedback de gameplay',
        level: 2,
        category: 'gameplay',
        categories: ['game_dev'],
        tags: ['VFX', 'Shuriken', 'Effects'],
        icon: 'particles',
        order: 10,
      },
      {
        name_pt: 'Universal Render Pipeline (URP)',
        name_en: 'Universal Render Pipeline (URP)',
        name_es: 'Universal Render Pipeline (URP)',
        description_pt: 'Pipeline de renderizacao otimizado para performance',
        description_en: 'Optimized render pipeline for performance',
        description_es: 'Pipeline de renderizado optimizado para rendimiento',
        level: 3,
        category: 'gameplay',
        categories: ['game_dev'],
        tags: ['Rendering', 'Shaders', 'Lighting'],
        icon: 'urp',
        order: 11,
      },
      {
        name_pt: 'Physics',
        name_en: 'Physics',
        name_es: 'Fisica',
        description_pt: 'Fisica 2D e 3D com rigidbodies e raycasting',
        description_en: '2D and 3D physics with rigidbodies and raycasting',
        description_es: 'Fisica 2D y 3D con rigidbodies y raycasting',
        level: 3,
        category: 'gameplay',
        categories: ['game_dev', 'gameplay'],
        tags: ['Rigidbody', 'Raycast', 'Collision'],
        icon: 'physics',
        order: 12,
      },
      {
        name_pt: 'Netcode for GameObjects',
        name_en: 'Netcode for GameObjects',
        name_es: 'Netcode for GameObjects',
        description_pt: 'Multiplayer em tempo real com Netcode da Unity',
        description_en: 'Real-time multiplayer with Unity Netcode',
        description_es: 'Multijugador en tiempo real con Unity Netcode',
        level: 1,
        category: 'frameworks',
        categories: ['game_dev', 'frameworks'],
        tags: ['Multiplayer', 'Networking', 'Sync'],
        icon: 'netcode',
        order: 13,
      },
      {
        name_pt: 'WebGL',
        name_en: 'WebGL',
        name_es: 'WebGL',
        description_pt: 'Exportacao e otimizacao de jogos para navegadores',
        description_en: 'Game export and optimization for browsers',
        description_es: 'Exportacion y optimizacion de juegos para navegadores',
        level: 2,
        category: 'gameplay',
        categories: ['game_dev'],
        tags: ['Browser', 'Optimization', 'Export'],
        icon: 'webgl',
        order: 14,
      },
      {
        name_pt: 'Mobile Development',
        name_en: 'Mobile Development',
        name_es: 'Mobile Development',
        description_pt: 'Desenvolvimento e otimizacao para iOS e Android',
        description_en: 'Development and optimization for iOS and Android',
        description_es: 'Desarrollo y optimizacion para iOS y Android',
        level: 2,
        category: 'gameplay',
        categories: ['game_dev'],
        tags: ['iOS', 'Android', 'Touch'],
        icon: 'mobile',
        order: 15,
      },
      {
        name_pt: 'Player Authentication',
        name_en: 'Player Authentication',
        name_es: 'Player Authentication',
        description_pt: 'Integracao de login e autenticacao de jogadores',
        description_en: 'Player login and authentication integration',
        description_es: 'Integracion de login y autenticacion de jugadores',
        level: 2,
        category: 'backend',
        categories: ['game_dev'],
        tags: ['Login', 'Security', 'Backend'],
        icon: 'auth',
        order: 16,
      },
      {
        name_pt: 'Cloud Save',
        name_en: 'Cloud Save',
        name_es: 'Cloud Save',
        description_pt: 'Persistencia de dados de jogo na nuvem',
        description_en: 'Game data persistence in the cloud',
        description_es: 'Persistencia de datos de juego en la nube',
        level: 2,
        category: 'backend',
        categories: ['game_dev'],
        tags: ['Save', 'Cloud', 'Sync'],
        icon: 'cloud-save',
        order: 17,
      },
      {
        name_pt: 'Coyote Time',
        name_en: 'Coyote Time',
        name_es: 'Coyote Time',
        description_pt: 'Janela de tolerancia para pulo apos sair da plataforma',
        description_en: 'Grace window for jumping after leaving platform',
        description_es: 'Ventana de tolerancia para salto tras dejar plataforma',
        level: 3,
        category: 'gameplay',
        categories: ['gameplay'],
        tags: ['Jump', 'Game Feel', 'Platformer'],
        icon: 'coyote',
        order: 18,
      },
      {
        name_pt: 'Jump Buffer',
        name_en: 'Jump Buffer',
        name_es: 'Jump Buffer',
        description_pt: 'Memoriza input de pulo antes de tocar o chao',
        description_en: 'Stores jump input before landing on ground',
        description_es: 'Memoriza input de salto antes de tocar el suelo',
        level: 3,
        category: 'gameplay',
        categories: ['gameplay'],
        tags: ['Jump', 'Input', 'Game Feel'],
        icon: 'jump-buffer',
        order: 19,
      },
      {
        name_pt: 'Wall Jump',
        name_en: 'Wall Jump',
        name_es: 'Wall Jump',
        description_pt: 'Pulo vertical em paredes com impulso direcional',
        description_en: 'Directional jump propelled from walls',
        description_es: 'Salto direccional impulsado desde paredes',
        level: 3,
        category: 'gameplay',
        categories: ['gameplay'],
        tags: ['Jump', 'Wall', 'Platformer'],
        icon: 'wall-jump',
        order: 20,
      },
      {
        name_pt: 'Wall Slide',
        name_en: 'Wall Slide',
        name_es: 'Wall Slide',
        description_pt: 'Deslizamento controlado em paredes com fisica',
        description_en: 'Controlled sliding on walls with physics',
        description_es: 'Deslizamiento controlado en paredes con fisica',
        level: 2,
        category: 'gameplay',
        categories: ['gameplay'],
        tags: ['Wall', 'Physics', 'Platformer'],
        icon: 'wall-slide',
        order: 21,
      },
      {
        name_pt: 'Dash',
        name_en: 'Dash',
        name_es: 'Dash',
        description_pt: 'Impulso rapido com invencibilidade temporaria',
        description_en: 'Quick burst with temporary invincibility',
        description_es: 'Impulso rapido con invencibilidad temporal',
        level: 3,
        category: 'gameplay',
        categories: ['gameplay'],
        tags: ['Movement', 'I-frames', 'Speed'],
        icon: 'dash',
        order: 22,
      },
      {
        name_pt: 'Input System',
        name_en: 'Input System',
        name_es: 'Input System',
        description_pt: 'Sistema moderno de input da Unity com action maps',
        description_en: 'Modern Unity input system with action maps',
        description_es: 'Sistema moderno de input de Unity con action maps',
        level: 2,
        category: 'gameplay',
        categories: ['gameplay'],
        tags: ['Input', 'Actions', 'Gamepad'],
        icon: 'input',
        order: 23,
      },
      {
        name_pt: 'Game Feel',
        name_en: 'Game Feel',
        name_es: 'Game Feel',
        description_pt: 'Juice: screen shake, hitstop, particulas e feedback',
        description_en: 'Juice: screen shake, hitstop, particles and feedback',
        description_es: 'Juice: screen shake, hitstop, particulas y feedback',
        level: 3,
        category: 'gameplay',
        categories: ['gameplay'],
        tags: ['Juice', 'Feedback', 'Polish'],
        icon: 'game-feel',
        order: 24,
      },
      {
        name_pt: 'Enemy Behaviors',
        name_en: 'Enemy Behaviors',
        name_es: 'Enemy Behaviors',
        description_pt: 'IA inimiga com NavMesh e Behavior Trees',
        description_en: 'Enemy AI with NavMesh and Behavior Trees',
        description_es: 'IA enemiga con NavMesh y Behavior Trees',
        level: 2,
        category: 'gameplay',
        categories: ['gameplay'],
        tags: ['AI', 'NavMesh', 'Behavior Tree'],
        icon: 'enemy-ai',
        order: 25,
      },
      {
        name_pt: 'Camera Systems',
        name_en: 'Camera Systems',
        name_es: 'Camera Systems',
        description_pt: 'Cameras dinamicas com follow, zoom e confiner',
        description_en: 'Dynamic cameras with follow, zoom and confiner',
        description_es: 'Cameras dinamicas con follow, zoom y confiner',
        level: 2,
        category: 'gameplay',
        categories: ['gameplay'],
        tags: ['Camera', 'Follow', 'Bounds'],
        icon: 'camera',
        order: 26,
      },
      {
        name_pt: 'Collision Detection',
        name_en: 'Collision Detection',
        name_es: 'Collision Detection',
        description_pt: 'Deteccao precisa com OverlapBox e Raycast',
        description_en: 'Precise detection with OverlapBox and Raycast',
        description_es: 'Deteccion precisa con OverlapBox y Raycast',
        level: 3,
        category: 'gameplay',
        categories: ['gameplay'],
        tags: ['Collision', 'Raycast', 'OverlapBox'],
        icon: 'collision',
        order: 27,
      },
      {
        name_pt: 'Checkpoint Systems',
        name_en: 'Checkpoint Systems',
        name_es: 'Checkpoint Systems',
        description_pt: 'Sistema de save points e respawn em jogos',
        description_en: 'Save point and respawn system for games',
        description_es: 'Sistema de save points y respawn en juegos',
        level: 2,
        category: 'gameplay',
        categories: ['gameplay'],
        tags: ['Checkpoint', 'Respawn', 'Save'],
        icon: 'checkpoint',
        order: 28,
      },
      {
        name_pt: 'C#',
        name_en: 'C#',
        name_es: 'C#',
        description_pt: 'Linguagem principal para Unity e desenvolvimento .NET',
        description_en: 'Primary language for Unity and .NET development',
        description_es: 'Lenguaje principal para Unity y desarrollo .NET',
        level: 3,
        category: 'languages',
        categories: ['languages'],
        tags: ['OOP', 'LINQ', '.NET'],
        icon: 'csharp',
        order: 29,
      },
      {
        name_pt: 'SQL',
        name_en: 'SQL',
        name_es: 'SQL',
        description_pt: 'Consultas e modelagem de banco de dados relacional',
        description_en: 'Relational database queries and modeling',
        description_es: 'Consultas y modelado de base de datos relacional',
        level: 2,
        category: 'languages',
        categories: ['languages'],
        tags: ['Database', 'Queries', 'RDBMS'],
        icon: 'sql',
        order: 30,
      },
      {
        name_pt: 'HTML5',
        name_en: 'HTML5',
        name_es: 'HTML5',
        description_pt: 'Estrutura semantica para web e WebGL games',
        description_en: 'Semantic structure for web and WebGL games',
        description_es: 'Estructura semantica para web y juegos WebGL',
        level: 2,
        category: 'languages',
        categories: ['languages'],
        tags: ['Web', 'Semantic', 'Canvas'],
        icon: 'html',
        order: 31,
      },
      {
        name_pt: 'CSS3',
        name_en: 'CSS3',
        name_es: 'CSS3',
        description_pt: 'Estilizacao e layout responsivo para interfaces web',
        description_en: 'Styling and responsive layout for web interfaces',
        description_es: 'Estilizacion y layout responsivo para interfaces web',
        level: 2,
        category: 'languages',
        categories: ['languages'],
        tags: ['Web', 'Layout', 'Responsive'],
        icon: 'css',
        order: 32,
      },
      {
        name_pt: 'Java',
        name_en: 'Java',
        name_es: 'Java',
        description_pt: 'Programacao orientada a objetos e desenvolvimento enterprise',
        description_en: 'Object-oriented programming and enterprise development',
        description_es: 'Programacion orientada a objetos y desarrollo enterprise',
        level: 1,
        category: 'languages',
        categories: ['languages'],
        tags: ['OOP', 'Enterprise', 'JVM'],
        icon: 'java',
        order: 33,
      },
      {
        name_pt: 'JavaScript',
        name_en: 'JavaScript',
        name_es: 'JavaScript',
        description_pt: 'Desenvolvimento web front-end e logica interativa',
        description_en: 'Web front-end development and interactive logic',
        description_es: 'Desarrollo web front-end y logica interactiva',
        level: 2,
        category: 'languages',
        categories: ['languages'],
        tags: ['Web', 'Frontend', 'ES6'],
        icon: 'javascript',
        order: 34,
      },
      {
        name_pt: 'ASP.NET MVC',
        name_en: 'ASP.NET MVC',
        name_es: 'ASP.NET MVC',
        description_pt: 'Framework MVC para aplicacoes web em C#',
        description_en: 'MVC framework for C# web applications',
        description_es: 'Framework MVC para aplicaciones web en C#',
        level: 2,
        category: 'backend',
        categories: ['backend', 'frameworks'],
        tags: ['MVC', 'Web', 'C#'],
        icon: 'aspnet',
        order: 35,
      },
      {
        name_pt: '.NET',
        name_en: '.NET',
        name_es: '.NET',
        description_pt: 'Plataforma de desenvolvimento multiplataforma da Microsoft',
        description_en: 'Microsoft cross-platform development platform',
        description_es: 'Plataforma de desarrollo multiplataforma de Microsoft',
        level: 2,
        category: 'backend',
        categories: ['backend', 'frameworks'],
        tags: ['Runtime', 'SDK', 'Cross-platform'],
        icon: 'dotnet',
        order: 36,
      },
      {
        name_pt: 'Entity Framework',
        name_en: 'Entity Framework',
        name_es: 'Entity Framework',
        description_pt: 'ORM para mapeamento objeto-relacional em .NET',
        description_en: 'ORM for object-relational mapping in .NET',
        description_es: 'ORM para mapeo objeto-relacional en .NET',
        level: 2,
        category: 'backend',
        categories: ['backend', 'frameworks'],
        tags: ['ORM', 'Migrations', 'LINQ'],
        icon: 'ef',
        order: 37,
      },
      {
        name_pt: 'SQL Server',
        name_en: 'SQL Server',
        name_es: 'SQL Server',
        description_pt: 'Banco de dados relacional corporativo da Microsoft',
        description_en: 'Microsoft enterprise relational database',
        description_es: 'Base de datos relacional corporativa de Microsoft',
        level: 2,
        category: 'backend',
        categories: ['backend'],
        tags: ['Database', 'T-SQL', 'Enterprise'],
        icon: 'sql-server',
        order: 38,
      },
      {
        name_pt: 'REST Integration',
        name_en: 'REST Integration',
        name_es: 'REST Integration',
        description_pt: 'APIs RESTful para integracao de servicos e jogos',
        description_en: 'RESTful APIs for service and game integration',
        description_es: 'APIs RESTful para integracion de servicios y juegos',
        level: 2,
        category: 'backend',
        categories: ['backend'],
        tags: ['API', 'REST', 'JSON'],
        icon: 'rest',
        order: 39,
      },
      {
        name_pt: 'Authentication Systems',
        name_en: 'Authentication Systems',
        name_es: 'Authentication Systems',
        description_pt: 'Sistemas de login, tokens e controle de acesso',
        description_en: 'Login, token and access control systems',
        description_es: 'Sistemas de login, tokens y control de acceso',
        level: 2,
        category: 'backend',
        categories: ['backend'],
        tags: ['JWT', 'OAuth', 'Security'],
        icon: 'auth-systems',
        order: 40,
      },
      {
        name_pt: 'Cloud Services',
        name_en: 'Cloud Services',
        name_es: 'Cloud Services',
        description_pt: 'Servicos em nuvem para deploy e escalabilidade',
        description_en: 'Cloud services for deployment and scalability',
        description_es: 'Servicios en la nube para deploy y escalabilidad',
        level: 1,
        category: 'backend',
        categories: ['backend'],
        tags: ['Cloud', 'Deploy', 'Azure'],
        icon: 'cloud-services',
        order: 41,
      },
      {
        name_pt: 'Unreal Engine',
        name_en: 'Unreal Engine',
        name_es: 'Unreal Engine',
        description_pt: 'Conhecimento em desenvolvimento 3D de alto nivel',
        description_en: 'Knowledge in high-end 3D development',
        description_es: 'Conocimiento en desarrollo 3D de alto nivel',
        level: 1,
        category: 'engines',
        categories: ['engines'],
        tags: ['3D', 'C++', 'Blueprints'],
        icon: 'unreal',
        order: 42,
      },
      {
        name_pt: 'Godot',
        name_en: 'Godot',
        name_es: 'Godot',
        description_pt: 'Conhecimento em motor open source para 2D e 3D',
        description_en: 'Knowledge in open source engine for 2D and 3D',
        description_es: 'Conocimiento en motor open source para 2D y 3D',
        level: 1,
        category: 'engines',
        categories: ['engines'],
        tags: ['Open Source', 'GDScript', '2D'],
        icon: 'godot',
        order: 43,
      },
      {
        name_pt: 'Visual Studio',
        name_en: 'Visual Studio',
        name_es: 'Visual Studio',
        description_pt: 'IDE principal para desenvolvimento C# e .NET',
        description_en: 'Primary IDE for C# and .NET development',
        description_es: 'IDE principal para desarrollo C# y .NET',
        level: 3,
        category: 'tools',
        categories: ['tools'],
        tags: ['IDE', 'Debugging', 'C#'],
        icon: 'vs',
        order: 44,
      },
      {
        name_pt: 'Visual Studio Code',
        name_en: 'Visual Studio Code',
        name_es: 'Visual Studio Code',
        description_pt: 'Editor leve para web, scripts e configuracoes',
        description_en: 'Lightweight editor for web, scripts and configs',
        description_es: 'Editor ligero para web, scripts y configuraciones',
        level: 3,
        category: 'tools',
        categories: ['tools'],
        tags: ['Editor', 'Extensions', 'Lightweight'],
        icon: 'vscode',
        order: 45,
      },
      {
        name_pt: 'Git',
        name_en: 'Git',
        name_es: 'Git',
        description_pt: 'Controle de versao distribuido para projetos',
        description_en: 'Distributed version control for projects',
        description_es: 'Control de version distribuido para proyectos',
        level: 3,
        category: 'versioning',
        categories: ['tools'],
        tags: ['VCS', 'Branching', 'Merge'],
        icon: 'git',
        order: 46,
      },
      {
        name_pt: 'GitHub',
        name_en: 'GitHub',
        name_es: 'GitHub',
        description_pt: 'Plataforma de hospedagem e colaboracao de codigo',
        description_en: 'Code hosting and collaboration platform',
        description_es: 'Plataforma de alojamiento y colaboracion de codigo',
        level: 3,
        category: 'versioning',
        categories: ['tools'],
        tags: ['Hosting', 'CI/CD', 'Collaboration'],
        icon: 'github',
        order: 47,
      },
      {
        name_pt: 'Unity Hub',
        name_en: 'Unity Hub',
        name_es: 'Unity Hub',
        description_pt: 'Gestao de instalacoes e projetos Unity',
        description_en: 'Manage Unity installations and projects',
        description_es: 'Gestion de instalaciones y proyectos Unity',
        level: 3,
        category: 'tools',
        categories: ['tools'],
        tags: ['Management', 'Installs', 'Projects'],
        icon: 'unity-hub',
        order: 48,
      },
      {
        name_pt: 'Unity Package Manager',
        name_en: 'Unity Package Manager',
        name_es: 'Unity Package Manager',
        description_pt: 'Gestao de pacotes e dependencias no Unity',
        description_en: 'Package and dependency management in Unity',
        description_es: 'Gestion de paquetes y dependencias en Unity',
        level: 2,
        category: 'tools',
        categories: ['tools'],
        tags: ['Packages', 'Dependencies', 'UPM'],
        icon: 'upm',
        order: 49,
      },
    ]

    try {
      var col = app.findCollectionByNameOrId('skills')
      for (var i = 0; i < skills.length; i++) {
        var s = skills[i]
        try {
          app.findFirstRecordByData('skills', 'name_en', s.name_en)
        } catch (_) {
          var r = new Record(col)
          r.set('name_pt', s.name_pt)
          r.set('name_en', s.name_en)
          r.set('name_es', s.name_es)
          r.set('description_pt', s.description_pt)
          r.set('description_en', s.description_en)
          r.set('description_es', s.description_es)
          r.set('level', s.level)
          r.set('category', s.category)
          r.set('categories', s.categories)
          r.set('tags', s.tags)
          r.set('icon', s.icon)
          r.set('order', s.order)
          app.save(r)
        }
      }
    } catch (err) {
      console.log('Seed skills error: ' + String(err))
    }
  },
  (app) => {
    try {
      var records = app.findRecordsByFilter('skills', "id != ''", '', 200, 0)
      for (var i = 0; i < records.length; i++) {
        app.delete(records[i])
      }
    } catch (_) {}
  },
)
